# -*- coding: utf-8 -*-
"""Copy of C02.matplotlib.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iE8aoiKUH2AM22GGgOmcWdTi2bJ6TQTx
"""

import matplotlib.pyplot as plt

y1 = []
y2 = []

x = range(-100, 100, 10)

for i in x:
    y1.append(i**2)

for i in x:
    y2.append(-i**2)

plt.plot(x, y1)
plt.plot(x, y2)

plt.xlabel("x")
plt.ylabel("y")
plt.ylim(-2000, 2000)

plt.axhline(0)
plt.axvline(0)

plt.savefig("quad.png")
plt.show()

import matplotlib.pyplot as plt

x_value = [0, 1, 2, 3, 4, 5]

y_value = [0, 1, 4, 9, 16, 25]

plt.scatter(x_value, y_value, s=30, color="blue")

plt.show()

import matplotlib.pyplot as plt

x_value = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

y_value = [2, 4, 5, 7, 6, 8, 9, 11, 12, 12, 13]

plt.scatter(x_value, y_value, label="stars", color="green", marker="*", s=30)

plt.xlabel('x - axis')
plt.ylabel('y - axis')

plt.title('My scatter plot!')

plt.legend()

plt.show()

import matplotlib.pyplot as plt
values = [5, 6, 3, 7, 2]
names =["A", "B", "C", "D", "E"]
plt.bar(names, values, color = "green")
plt.show()

import matplotlib.pyplot as plt
values = [5, 6, 3, 7, 2]
names =["A", "B", "C", "D", "E"]
plt.barh(names, values, color = "green")
plt.show()

import matplotlib.pyplot as plt

height = [10, 24, 36, 40, 5]

names = ["one", "two", "three", "four", "five"]

c1 = ['red', 'green', 'blue', 'yellow', 'orange']

plt.bar(names, height, width=0.8, color=c1)

plt.xlabel('x - axis')
plt.ylabel('y - axis')

plt.title('My bar chart!')

plt.show()

from sklearn.datasets import load_iris
import pandas as pd

iris = load_iris()

df = pd.DataFrame(
    iris.data,
    columns=[
        'sepal length (cm)',
        'sepal width (cm)',
        'petal length (cm)',
        'petal width (cm)'
    ]
)

print(df.head())

import matplotlib.pyplot as plt

plt.subplot(2, 3, 1)
plt.plot(df['sepal length (cm)'], df['petal width (cm)'])

plt.subplot(2, 3, 2)
plt.plot(df['sepal width (cm)'], df['petal width (cm)'])

plt.subplot(2, 3, 3)
plt.scatter(df['sepal length (cm)'], df['petal width (cm)'])

plt.subplot(2, 3, 4)
plt.scatter(
    df['sepal width (cm)'],
    df['petal length (cm)'],
    c='green'
)

plt.title('Subplots')

plt.show()

import matplotlib.pyplot as plt

plt.hist(df['sepal length (cm)'])

plt.xlabel('Sepal Length')
plt.ylabel('Frequency')

plt.title('Histogram')

plt.show()

!pip install dash

import dash
from dash import dcc, html


print(dash.version)

import dash
from dash import dcc, html

app = dash.Dash(__name__)

app.layout = html.Div([
    html.H1("Dash Tutorial"),

    dcc.Graph(
        id="example",
        figure={
            "data": [
                {
                    "x": [1, 2, 3, 4, 5],
                    "y": [5, 4, 7, 4, 8],
                    "type": "line",
                    "name": "Tracks"
                },
                {
                    "x": [1, 2, 3, 4, 5],
                    "y": [6, 3, 5, 3, 7],
                    "type": "bar",
                    "name": "Ships"
                }
            ],
            "layout": {
                "title": "Data Tutorial"
            }
        }
    )
])

#if __name__ == "__main__":
#    app.run(debug=True)
app.run(debug=True, port=8081)

from dash import Input, Output
id = 'input'
id = 'output'

import dash
from dash import dcc, html, Input, Output

app = dash.Dash(__name__)

app.layout = html.Div([
    html.Div("Square Calculator"),

    dcc.Input(
        id="input",
        type="text",
        placeholder="Enter a Number"
    ),

    html.Div(
        id="output"
    )
])

@app.callback(
    Output(component_id="output", component_property="children"),
    Input(component_id="input", component_property="value")
)
def update_value(input_data):
    try:
        return str(float(input_data) ** 2)
    except:
        return "Error: The input is not a number"

app.run(debug=True)

